#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

version: 2.1
commands:
  install-bazel:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/linux.sh
      - run: bash ./linux.sh && rm ./linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/rbe.sh
      - run: bash ./rbe.sh && rm ./rbe.sh

  run-bazel:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_dependencies//tool/bazelrun:rbe -- << parameters.command >>

jobs:
  build:
    machine: true
    working_directory: ~/grakn
    steps:
      - install-bazel
      - checkout
      - run-bazel:
          command: bazel build //...
      - run:
          name: Verify dependencies/maven/artifacts.snapshot
          command: |
            dependencies/maven/update.sh
            git diff --exit-code dependencies/maven/artifacts.snapshot
      - run: bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list

  build-checkstyle:
    machine: true
    working_directory: ~/grakn
    steps:
      - install-bazel
      - checkout
      - run: bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
      - run-bazel:
          command: bazel test $(bazel query 'kind(checkstyle_test, //...)')

  build-analysis:
    machine: true
    working_directory: ~/grakn
    steps:
      - install-bazel
      - checkout
      - run: |
          SONARCLOUD_CODE_ANALYSIS_CREDENTIAL=$SONARCLOUD_CREDENTIAL \
            bazel run @graknlabs_dependencies//tool/sonarcloud:code-analysis -- \
            --organisation=$SONARCLOUD_ORGANISATION \
            --project-key=$SONARCLOUD_PROJECT_KEY \
            --commit-id=$CIRCLE_SHA1 \
            --branch=$CIRCLE_BRANCH

  test-basic:
    machine: true
    working_directory: ~/grakn
    steps:
      - install-bazel
      - checkout
      - run-bazel:
          command: bazel test //test/integration:test-basic --test_output=errors

  test-connection:
    machine: true
    working_directory: ~/grakn
    steps:
      - install-bazel
      - checkout
      - run-bazel:
          command: bazel test //test/behaviour/connection/database:test --test_output=errors
      - run-bazel:
          command: bazel test //test/behaviour/connection/session:test --test_output=errors
      - run-bazel:
          command: bazel test //test/behaviour/connection/transaction:test --test_output=errors

  test-concept:
    machine: true
    working_directory: ~/grakn
    steps:
      - install-bazel
      - checkout
      - run-bazel:
          command: bazel test //test/behaviour/concept/type/entitytype:test --test_output=errors
      - run-bazel:
          command: bazel test //test/behaviour/concept/type/relationtype:test --test_output=errors
      - run-bazel:
          command: bazel test //test/behaviour/concept/type/attributetype:test --test_output=errors
      - run-bazel:
          command: bazel test //test/behaviour/concept/thing/entity:test --test_output=errors
      - run-bazel:
          command: bazel test //test/behaviour/concept/thing/attribute:test --test_output=errors
      - run-bazel:
          command: bazel test //test/behaviour/concept/thing/relation:test --test_output=errors

  test-query:
    machine: true
    working_directory: ~/grakn
    steps:
      - install-bazel
      - checkout
      - run-bazel:
          command: bazel test //test/integration:test-query --test_output=errors

workflows:
  grakn:
    jobs:
      - build
      - build-checkstyle
      - build-analysis
      - test-basic
      - test-connection
      - test-concept
      - test-query
